### ISSUE TITLE
Cannot define attribute named `method`

### ISSUE THREAD

**Issue by arangamani** [rightscale/attributor#99] opened 2015-01-19 23:35 UTC
When I try to define an attribute named `:method`, I get the following error:
```
Attributor::DumpError: Error while dumping attribute method of type V1::MediaTypes::Hello for context $. Reason: wrong number of arguments (0 for 1)

ArgumentError: wrong number of arguments (0 for 1)
```

This is possibly related to #71

**Comment by blanquer** [comment] 2015-01-27 23:42
@arangamani  the models are still backed by normal ruby objects (i.e. Object class), therefore there are some methods that cannot be used as attributes as they already exist (because or ruby, or really, other libraries that might inject and intercept them).
What #71 describes is to migrate the backing object to BasicObject which is a blank slate, but unfortunately, that is not necessarily a cakewalk to do...so we'll have to see about the interest and priorities of other issues I guess.

**Comment by careo** [comment] 2015-10-30 23:35
Duplicate of #71, as that's really how we should end up fixing this.

**Closed by careo** 2015-10-30 23:35 UTC
